/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class sd_gui_libAvifHeicJNI */

#ifndef _Included_sd_gui_libAvifHeicJNI
#define _Included_sd_gui_libAvifHeicJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     sd_gui_libAvifHeicJNI
 * Method:    AvifHeicDecode
 * Signature: ([BJI[I[I[I[J)[I
 */
JNIEXPORT jintArray JNICALL Java_sd_gui_libAvifHeicJNI_AvifHeicDecode
  (JNIEnv *, jclass, jbyteArray, jlong, jint, jintArray, jintArray, jintArray, jlongArray);

/*
 * Class:     sd_gui_libAvifHeicJNI
 * Method:    AvifHeicWrite
 * Signature: (Ljava/io/OutputStream;[[IIIII[J)Z
 */
JNIEXPORT jboolean JNICALL Java_sd_gui_libAvifHeicJNI_AvifHeicWrite
  (JNIEnv *, jclass, jobject, jobjectArray, jint, jint, jint, jint, jlongArray);

#ifdef __cplusplus
}
#endif
#endif
